import React from 'react';

function About() {
  return (
    // Contenedor para informacion personal y descripcion de la aplicacion
    <div className="about">
      <h1>Acerca de Kodigo Music</h1>
      <p>
        Kodigo Music es una aplicación web de una sola página (SPA) inspirada en las principales plataformas de música digital. Permite explorar álbumes, ver detalles de canciones y agregar nueva música de forma sencilla y atractiva. Está desarrollada con ReactJS y cuenta con un diseño moderno y responsive para brindar la mejor experiencia al usuario.
      </p>
    </div>
  );
}

export default About;