import React from 'react';

function About() {
  return (
    // Contenedor para informacion personal y descripcion de la aplicacion
    <div className="about">
      <h1>Acerca de Kodigo Music</h1>
      <p>
        Kodigo Music es una aplicación web de una sola página inspirada en las principales plataformas de música digital. Permite explorar álbumes y ver detalles de canciones de forma sencilla y atractiva. 
      </p>
    </div>
  );
}

export default About;